name: Unpublish

on: [workflow_dispatch]

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.11.1
          registry-url: https://registry.npmjs.org
      - name: unpublish
        run: npm unpublish ghtest-a --force && npm unpublish ghtest-b --force
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: unpublish ws
        run: npm unpublish ghtest-a --force --workspaces && npm unpublish ghtest-b --force --workspaces
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
